name: PIO

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m venv pioenv
        ./pioenv/bin/pip install platformio
    - name: Run the test
      run: |
        ./pioenv/bin/platformio run
